# Model Configuration for Induction Hardening FNO
# =================================================

model:
  name: "ParallelUFNO"
  
  # Model Hyperparameters
  n_modes: [16, 16] 
  
  # hidden_channels: Width of the network. 
  hidden_channels: 32
  
  # n_layers: Number of Fourier Layers. 
  n_layers: 4
  
  # U-Net Hyperparameters
  encoder_name: "resnet18"
  encoder_weights: null
  
  # Input/Output Dimensions
  in_channels: 5  # 2D Coord + freq + Temp Init + current
  out_channels: 4 # Temp + 3 Phases

loss:
  alpha: 5.0 # MSE/CE Weight
  beta: 2.0  # Sobel Weight
  gamma: 0.0 # Physics Weight (Disabled)

training:
  # Optimization
  batch_size: 64
  epochs: 200
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  
  # Scheduler settings (StepLR)
  scheduler:
    step_size: 50
    gamma: 0.8
    
  # Early Stopping
  early_stopping:
    patience: 30
    min_delta: 1.0e-5

  # Checkpoint
  load_from_checkpoint: null # Path to .pth file to resume training (e.g., "outputs/models_weights/best_model.pth")

  # Hardware
  device: "cuda"  # Use "cpu" if no GPU is available
